# Generated by Django 5.0.2 on 2024-02-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_name', models.CharField(max_length=200)),
                ('products_price', models.CharField(max_length=200)),
                ('product_quantity', models.IntegerField(null=True)),
            ],
        ),
    ]
